### ISSUE TITLE
scripty ERR! It seems you may be running scripty from the command-line directly

### ISSUE THREAD

**Issue by laterdayi** [testdouble/scripty#118]
pnpm install is normal, but it prompts in the case o·f cnpm install and yarn

```
scripty ERR! It seems you may be running scripty from the command-line directly.
At this time, scripty can only be run within an npm script specified in your package.json.

Example package.json entry:

  "scripts": {
    "foo:bar": "scripty"
  }

And then run via `npm run foo:bar`.

For more documentation, see:
  https://github.com/testdouble/scripty
```

@jasonkarns

**Comment by laterdayi** [comment]
```
> scripty
scripty ERR! It seems you may be running scripty from the command-line directly.
At this time, scripty can only be run within an npm script specified in your package.json.

Example package.json entry:

  "scripts": {
    "foo:bar": "scripty"
  }

And then run via `npm run foo:bar`.

For more documentation, see:
  https://github.com/testdouble/scripty

Exiting.
[npminstall:runscript:error] run prepare scripty error: Error: Command failed with exit code 1: scripty
    at makeError (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.runScript (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\lib\utils.js:262:12)
    at async runLifecycleScripts (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:64:7)
    at async _install (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:167:5)
    at async module.exports (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:86:5)
    at async F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\bin\install.js:480:5 {
  shortMessage: 'Command failed with exit code 1: scripty',
  command: 'scripty',
  escapedCommand: 'scripty',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
> prepare, finished in 87ms
× Install fail! Error: run prepare error, please remove node_modules before retry!
Command failed with exit code 1: scripty
Error: Command failed with exit code 1: scripty
    at makeError (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.runScript (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\lib\utils.js:262:12)
    at async runLifecycleScripts (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:64:7)
    at async _install (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:167:5)
    at async module.exports (F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:86:5)
    at async F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\bin\install.js:480:5
npminstall version: 7.5.2
npminstall argv: F:\node\node.exe F:\nvm\v19.7.0\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\admin\.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com
```
