### ISSUE TITLE
Scripts fail with Node.js v >=18

### ISSUE THREAD

**Issue by nmonastyrskyi** [testdouble/scripty#121]
### Description:
When running scripts using Node.js with the version 18 and above - I have the next error:

```
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at module.exports (/Users/hardwork/Desktop/www/Agent/node_modules/scripty/lib/run/spawn-script.js:8:17)
    at /Users/hardwork/Desktop/www/Agent/node_modules/scripty/lib/run/index.js:4:27
    at /Users/hardwork/Desktop/www/Agent/node_modules/scripty/node_modules/async/dist/async.js:3883:24
    at replenish (/Users/hardwork/Desktop/www/Agent/node_modules/scripty/node_modules/async/dist/async.js:1014:17)
    at /Users/hardwork/Desktop/www/Agent/node_modules/scripty/node_modules/async/dist/async.js:1019:9
    at eachOfLimit (/Users/hardwork/Desktop/www/Agent/node_modules/scripty/node_modules/async/dist/async.js:1044:24)
    at /Users/hardwork/Desktop/www/Agent/node_modules/scripty/node_modules/async/dist/async.js:1049:16
    at _parallel (/Users/hardwork/Desktop/www/Agent/node_modules/scripty/node_modules/async/dist/async.js:3882:5) {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}
```

### Env versions
**Node.js** v`18.17.0`
**npm** v`9.6.7`
**OS** MacOS Intel

**Comment by telephant** [comment]
+1

**Comment by bruce-ws** [comment]
+1

**Comment by bruce-ws** [comment]
node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at module.exports (/xxxxxxxxxxxxxx/node_modules/.pnpm/scripty@2.1.1/node_modules/scripty/lib/run/spawn-script.js:8:17)
    at /xxxxxxxxxxxxxx/node_modules/.pnpm/scripty@2.1.1/node_modules/scripty/lib/run/index.js:4:27
    at /Users/brucew/jc/jc_monorepo/node_modules/.pnpm/async@2.6.4/node_modules/async/dist/async.js:3883:24
    at replenish (/xxxxxxxxxxxxxx/node_modules/.pnpm/async@2.6.4/node_modules/async/dist/async.js:1014:17)
    at /xxxxxxxxxxxxxx/node_modules/.pnpm/async@2.6.4/node_modules/async/dist/async.js:1019:9
    at eachOfLimit (/xxxxxxxxxxxxxxo/node_modules/.pnpm/async@2.6.4/node_modules/async/dist/async.js:1044:24)
    at /xxxxxxxxxxxxxx/node_modules/.pnpm/async@2.6.4/node_modules/async/dist/async.js:1049:16
    at _parallel (/xxxxxxxxxxxxxx/node_modules/.pnpm/async@2.6.4/node_modules/async/dist/async.js:3882:5) {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}


node  20.12.0
pnpm 9.1.1
