### ISSUE TITLE
Issue while running scripty on windows

### ISSUE THREAD

**Issue by vsawant1608** [testdouble/scripty#92]
I have below package.json file
```
{
  "name": "scripty-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "node app.js",
    "foo": "scripty"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cross-spawn": "^7.0.3",
    "express": "^4.17.1"
  },
  "devDependencies": {
    "scripty": "^2.0.0"
  },
  "scripty": {
    "logLevel": "verbose"
  }
}
```

and below is '/scripts/foo.sh'
```
echo "Hello";
```

When I run 
`npm run foo` getting below error on windows.
```
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at module.exports (D:\Explore\scripty-issue\node_modules\scripty\lib\run\spawn-script.js:8:17)
    at cb (D:\Explore\scripty-issue\node_modules\scripty\lib\run\index.js:4:27)
    at D:\Explore\scripty-issue\node_modules\async\dist\async.js:3880:24
    at replenish (D:\Explore\scripty-issue\node_modules\async\dist\async.js:1011:17)
    at D:\Explore\scripty-issue\node_modules\async\dist\async.js:1016:9
    at eachOfLimit (D:\Explore\scripty-issue\node_modules\async\dist\async.js:1041:24)
    at D:\Explore\scripty-issue\node_modules\async\dist\async.js:1046:16
    at _parallel (D:\Explore\scripty-issue\node_modules\async\dist\async.js:3879:5)
```

Just works fine on ubuntu. Any pointers would be helpful. I tried passing {shell:true} in ```node_modules\scripty\lib\run\spawn-script.js:8:17``` and it just worked fine.

**Comment by GiancarlosIO** [comment]
Same here 😢

**Comment by NormalReedus** [comment]
Same here. Have tried clearing NPM cache and clearing out `node_modules`. Scripty exclaims that it can find the script and tries to execute it. The script is executable and works when run directly with bash.

**Comment by sanketphansekar** [comment]
@vsawant1608 I feel the mistake might be in creating the script file, it should be with extension `.cmd`

As per documentation : **In order to add Windows support, you could define `scripts-win/script.cmd` **

For more details on windows support you can read it [here](https://github.com/testdouble/scripty#windows-support)

**Comment by dealvz** [comment]
@sanketphansekar followed those instructions, however what if the script is type `#!/usr/bin/env node` ?

**Comment by jonrcrowell** [comment]
I was having the same issue regardless of how I configured the shebang. (node, cmd, pwsh, bash, whatever)
I also deleted node_modules, any .lock files I had, and re-ran yarn.

I was able to get it to work by running `wsl` from the terminal, then running my scripty script. You'll need to have windows subsystem linux configured for this to work.

I have both a **/scripts** folder and a **/scripts-win** folder. The version that gets called from the wsl prompt is the **/scripts** version, which I actually prefer so that I don't have to maintain two sets of scripts.

**Comment by vsawant1608** [comment]
Just a hack for this would be to update file in node_modules to use 'cross_spawn'. It makes most of the things work fine on windows without any issues.

![image](https://user-images.githubusercontent.com/35254261/122441914-a80a1880-cfbb-11eb-8578-f318eb6ec450.png)

**Comment by andredezzy** [comment]
Any news?
